### ISSUE TITLE
Tap outside of select

### ISSUE THREAD

**Issue by ezequiel88** [m3uzz/select_form_field#6]
I'm getting an error when I tap outside the select to cancel.

Erro:
```
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: Bad state: No element
#0      ListMixin.firstWhere (dart:collection/list.dart:167:5)
#1      _SelectFormFieldState._showSelectFormFieldMenu (package:select_form_field/select_form_field.dart:524:29)
<asynchronous suspension>
```

.dart:
```
SelectFormField(
  controller: _categoria,
  labelText: 'Categoria',
  items: _items,
  decoration: InputDecoration(
    labelText: "Categoria",
    border: OutlineInputBorder(),
  ),
  onChanged: (val) => print(val),
  onSaved: (val) => print(val),
  validator: (value) {
    if (value == null || value.isEmpty) {
    return 'Selecione uma Categoria';
    }
    return null;
  },
),
```

items provider:

```
final List<Map<String, dynamic>> _items = [
    {
      'value': 'despesa',
      'label': 'Despesas',
    },
    {
      'value': 'receita',
      'label': 'Receitas',
    },
    {
      'value': 'pagar',
      'label': 'Contas a Pagar',
    },
    {
      'value': 'receber',
      'label': 'Contas a Receber',
    },
  ];
```

pubspec.yaml:

```
environment:
  sdk: ">=2.12.0 <3.0.0"

select_form_field: ^2.0.0
```

**Comment by shiminasai** [comment]
hi @ezequiel88, i have the same problem as you solved it

**Comment by ezequiel88** [comment]
> oi @ ezequiel88 , estou com o mesmo problema que você resolveu?

Não ainda.

**Comment by cjcv123** [comment]
I got the same error

**Comment by childon4god** [comment]
I have same issue

**Comment by LuisFerRosas** [comment]
mismo problema , cuando lo solucionaran?

**Comment by hslbetto** [comment]
The bug has been fixed and the new version is now available
